/*==============================================================================
 Project      : Olist E-commerce Business Analysis
 Module       : 07 - Advanced SQL Analysis
 Author       : Avushatha TN

 Description  : This module applies advanced SQL techniques to analyse
                customer behaviour, seller performance, product performance,
                delivery efficiency and revenue trends.

 Objective:
    • Perform advanced business analysis
    • Apply Joins, CTEs and Window Functions
    • Generate business insights
    • Prepare data for dashboard development

==============================================================================*/

/*------------------------------------------------------------------------------
 Analysis       : Top Customers by Spending

 Description:
    Identify customers who have spent the highest amount.

 Business Purpose:
    Helps identify high-value customers for loyalty programmes and
    targeted marketing campaigns.
------------------------------------------------------------------------------*/

SELECT
    o.customer_id,
    ROUND(SUM(p.payment_value),2) AS Total_Spent
FROM fact_orders o
JOIN fact_payments p
ON o.order_id = p.order_id
GROUP BY o.customer_id
ORDER BY Total_Spent DESC
LIMIT 10;

/*------------------------------------------------------------------------------
 Analysis       : Top Sellers by Orders

 Description:
    Identify sellers who fulfilled the highest number of order items.

 Business Purpose:
    Measures seller activity and marketplace contribution.
------------------------------------------------------------------------------*/

SELECT
    seller_id,
    COUNT(*) AS Total_Order_Items
FROM fact_order_items
GROUP BY seller_id
ORDER BY Total_Order_Items DESC
LIMIT 10;

/*------------------------------------------------------------------------------
 Analysis       : Product Category Revenue

 Description:
    Calculate total revenue generated by each product category.

 Business Purpose:
    Identify the most profitable product categories.
------------------------------------------------------------------------------*/

SELECT
    pct.product_category_name_english,
    ROUND(SUM(oi.price),2) AS Total_Revenue
FROM fact_order_items oi
JOIN dim_products p
ON oi.product_id = p.product_id
JOIN product_category_translation pct
ON p.product_category_name = pct.product_category_name
GROUP BY pct.product_category_name_english
ORDER BY Total_Revenue DESC
LIMIT 10;

/*------------------------------------------------------------------------------
 Analysis       : Best Selling Products

 Description:
    Identify the products with the highest number of sales.

 Business Purpose:
    Helps understand customer demand and inventory priorities.
------------------------------------------------------------------------------*/

SELECT
    product_id,
    COUNT(*) AS Total_Sales
FROM fact_order_items
GROUP BY product_id
ORDER BY Total_Sales DESC
LIMIT 10;

/*------------------------------------------------------------------------------
 Analysis       : Average Delivery Time

 Description:
    Calculate the average number of days taken to deliver orders.

 Business Purpose:
    Measures delivery efficiency.
------------------------------------------------------------------------------*/

SELECT
    ROUND(
        AVG(
            DATEDIFF(order_delivered_customer_date,
                     order_purchase_timestamp)
        ),2
    ) AS Average_Delivery_Days
FROM fact_orders
WHERE order_delivered_customer_date IS NOT NULL;

/*------------------------------------------------------------------------------
 Analysis       : Late Deliveries

 Description:
    Count orders delivered after the estimated delivery date.

 Business Purpose:
    Helps monitor delivery performance.
------------------------------------------------------------------------------*/

SELECT
    COUNT(*) AS Late_Deliveries
FROM fact_orders
WHERE order_delivered_customer_date >
      order_estimated_delivery_date;
      
      /*------------------------------------------------------------------------------
 Analysis       : Early Deliveries

 Description:
    Count orders delivered on or before the estimated delivery date.

 Business Purpose:
    Measures fulfilment efficiency.
------------------------------------------------------------------------------*/

SELECT
    COUNT(*) AS On_Time_or_Early_Deliveries
FROM fact_orders
WHERE order_delivered_customer_date <=
      order_estimated_delivery_date;
      
      /*------------------------------------------------------------------------------
 Analysis       : Monthly Revenue Ranking

 Description:
    Rank each month based on total revenue.

 Business Purpose:
    Identify the highest-performing months.
------------------------------------------------------------------------------*/

SELECT
    DATE_FORMAT(o.order_purchase_timestamp,'%Y-%m') AS Order_Month,
    ROUND(SUM(p.payment_value),2) AS Revenue,
    RANK() OVER(
        ORDER BY SUM(p.payment_value) DESC
    ) AS Revenue_Rank
FROM fact_orders o
JOIN fact_payments p
ON o.order_id = p.order_id
GROUP BY Order_Month;

/*------------------------------------------------------------------------------
 Analysis       : Seller Revenue Ranking

 Description:
    Rank sellers based on total revenue.

 Business Purpose:
    Compare seller performance across the marketplace.
------------------------------------------------------------------------------*/

SELECT
    seller_id,
    ROUND(SUM(price),2) AS Revenue,
    DENSE_RANK() OVER(
        ORDER BY SUM(price) DESC
    ) AS Seller_Rank
FROM fact_order_items
GROUP BY seller_id;

/*------------------------------------------------------------------------------
 Analysis       : Customer Purchase Ranking

 Description:
    Rank customers based on their total spending.

 Business Purpose:
    Identify premium customers for retention strategies.
------------------------------------------------------------------------------*/

SELECT
    o.customer_id,
    ROUND(SUM(p.payment_value),2) AS Total_Spent,
    ROW_NUMBER() OVER(
        ORDER BY SUM(p.payment_value) DESC
    ) AS Customer_Rank
FROM fact_orders o
JOIN fact_payments p
ON o.order_id = p.order_id
GROUP BY o.customer_id;

